### ISSUE TITLE
Not Working on Flarum 1.8.4

### ISSUE THREAD

**Issue by Litalino** [JeromeGillard/flarum-map#15]
Error link Rss or Atom

After the error does not work

Enable PLugin Error flarum.ERROR: InvalidArgumentException: No hint path defined for [flarum-feeds]. in /public_html/vendor/illuminate/view/FileViewFinder.php:112

https://discuss.flarum.org/d/31732-map-extension-display-a-map-a-gpx-or-a-geojson-file-in-a-post/15

Specifically, when updating flarum 1.5.3 and fof-upload 1.5.3, this utility causes a page-wide error:
flarum.ERROR: InvalidArgumentException: Failed importing jeromegillard-map due to View [jeromegillard-map] not found. in /public_html/vendor/fof/upload/src/Extenders/AddPostDownloadTags.php:52

I'm trying my way: https://github.com/JeromeGillard/flarum-map/pull/12/commits/32e4c2e0cb9fb9e6c0dbed9161d3591c0a6c9546

The website connects well but reports an error with the utility: : https://github.com/imorland/syndication

and extension: https://github.com/FriendsOfFlarum/upload when viewing file while uploading is empty in user info section

**Comment by JeromeGillard** [comment]
I could make [v0.1.9](https://packagist.org/packages/jeromegillard/map#v0.1.9) work with Flarum 1.8.4.  
Could you try on your side?

**Comment by Litalino** [comment]
> Tôi có thể làm cho [v0.1.9](https://packagist.org/packages/jeromegillard/map#v0.1.9) hoạt động với Flarum 1.8.4. Bạn có thể thử về phía bạn?

I just received information from you.. I will update.. If there are any errors, I will respond later

**Comment by Litalino** [comment]
Error not show media file link :https://domain/u/name_user/uploads


TypeError: t.canViewInfo is not a function
    at i.actionItems (DisplayFile.tsx:118:10)
    at i.view (DisplayFile.tsx:81:49)
    at Function.a (render.js:30:16)
    at render.js:155:45
    at render.js:160:3
    at c (render.js:66:8)
    at l (render.js:50:5)
    at render.js:134:5
    at c (render.js:63:14)
    at l (render.js:50:5)

And error rss : https://domain/atom : An error occurred while trying to load this page. 

[2023-12-28 04:06:11] flarum.ERROR: InvalidArgumentException: No hint path defined for [flarum-feeds]. in /home/public_html/vendor/illuminate/view/FileViewFinder.php:112

**Comment by JeromeGillard** [comment]
I guess this error is related to the `flarum-feeds` extension. Could you confirm by disabling it temporary and clearing the cache?
